spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaMessageProduceTopic: "order-topic"
    kafkaMessageConsumeTopic: "order-status-topic"
    kafkaMessageGroupId: "kafka-message-group-id"
